AllCops:
  Exclude:
    - db/**/*.rb
    - bin/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb

Metrics/LineLength:
  Max: 120

Style/NestedParenthesizedCalls:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
