AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb
    - lib/tasks/auto_annotate_models.rake
    - spec/**/*_spec.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/**/*

Style/NestedParenthesizedCalls:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
