version: '2'

services:
  app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - public:/app/public
      - /var/run/postgresql/:/var/run/postgresql/
    depends_on:
      - sidekiq
      - redis
    links:
      - sidekiq
      - redis
    env_file:
      - thalariond.env
    restart: always
  sidekiq:
    build: .
    volumes:
      - /var/run/postgresql/:/var/run/postgresql/
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - thalariond.env
    restart: always
    command: bundle exec sidekiq
  redis:
    image: redis
    volumes:
      - redis:/data
    restart: always

volumes:
  public: {}
  redis: {}
