default: &default
  adapter: postgresql
  host: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: thalariond_development

test:
  <<: *default
  database: thalariond_test

production:
  <<: *default
  database: thalariond_production
