# LDAP configuration
# Be aware that spring uses port 1389 for some reason
default: &default
  port: 2389
  base_dn: dc=thalarion,dc=be

development:
  <<: *default

production:
  <<: *default
  ssl_cert: ldap.cert
  ssl_key: ldap.key

test:
  <<: *default
