base_dn: <%= ENV['LDAPD_BASEDN'] %>

<% if ENV.has_key? 'LDAPD_BINDADDR' %>
bindaddr: <%= ENV['LDAPD_BINDADDR'] %>
<% end %>
<% if ENV.has_key? 'LDAPD_PORT' %>
port: <%= ENV['LDAPD_PORT'] %>
<% end %>
<% if ENV.has_key? 'LDAPD_SOCKET' %>
socket: <%= ENV['LDAPD_SOCKET'] %>
<% end %>
<% if ENV.has_key? 'LDAPD_SSL_CERT' %>
ssl_cert: <%= ENV['LDAPD_SSL_CERT'] %>
<% end %>
<% if ENV.has_key? 'LDAPD_SSL_KEY' %>
ssl_key: <%= ENV['LDAPD_SSL_KEY'] %>
<% end %>
<% if ENV.has_key? 'LDAPD_SSL_CA_PATH' %>
ssl_ca_path: <%= ENV['LDAPD_CA_PATH'] %>
<% end %>
<% if ENV.has_key? 'LDAPD_SSL_DHPARAMS' %>
ssl_dhparams: <%= ENV['LDAPD_DHPARAMS'] %>
<% end %>
